name: 'Build Docker image & Push to registry' 
on: 
  push:
    paths-ignore: 
      - '.github/**'
      - '**.py'
  workflow_dispatch:
    
  
jobs:
   build:
       runs-on: ubuntu-latest
     
       steps:
          - uses: actions/checkout@v2  
          - name: Login to DockerHub
            uses: docker/login-action@v1 
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: ${{ secrets.DOCKERHUB_USER }}/hello:latest
