name: Push to docker hub
on: [ pull_request, workflow_dispatch ]
  
jobs:
   build:
       runs-on: ubuntu-latest
     
       steps:
          - uses: actions/checkout@v2  
          - name: Login to DockerHub
          - uses: docker/login-action@v1 
            with:
              username: chandra25ms
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              push: true
              tags: chandra25ms/hello:latest
