name: Upload artifacts
on:
  push:
 
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout autotune
        uses: actions/checkout@v2
        run:
           echo "hello world" > "helloworld.txt"
           
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
           name: results
           path: ./helloworld.txt
           retention-days: 1
